Sys.info()

# required packages

library(tidytuesdayR)
library(tidyverse)
library(ggtext)
library(showtext)
library(scales)
library(grid)
library(ggfun)

# Load data from tidy tuesday - Paper: https://www.cell.com/patterns/fulltext/S2666-3899(23)00130-7?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS2666389923001307%3Fshowall%3Dtrue
tuesdata <- tidytuesdayR::tt_load(2023, week = 29)

detectors <- tuesdata$detectors

Human_detect <- detectors |>
  filter(kind == "Human") |>
  select(kind, .pred_AI, .pred_class, detector, native)

human_summary <- detectors |>
  filter(kind == "Human") |>
  select(.pred_class, detector, native) |>
  rename(pred_class = .pred_class) |>
  mutate(detector = as.factor(detector)) |>
  mutate(pred_class = as.factor(pred_class)) |>
  group_by(detector, native, pred_class) |>
  summarise(count = n()) |>
  group_by(detector, native) |>
  mutate(percent = round(count /sum(count) * 100)) 

human_summary$detector <- factor(human_summary$detector, 
                                 levels = c("ZeroGPT","GPTZero","Crossplag","HFOpenAI","Sapling", "OriginalityAI", "Quil"))

# fonts
font_add("datacontrol", "/Users/sejaldavla/Desktop/Data_Portfolio/GPT_Detectors/data-latin.ttf")
font_add("brassmono", "/Users/sejaldavla/Desktop/Data_Portfolio/GPT_Detectors/BrassMono/regular.otf")
font_install(google_fonts(name = "Ubuntu Mono"))
showtext_auto()  

# plot

col_pal <- c("ZeroGPT" = "#d16ba5",
             "GPTZero" = "#ba83ca",
             "Crossplag" = "#aa8fd8",
             "HFOpenAI"="#8aa7ec",
             "Sapling" = "#69bff8",
             "OriginalityAI" = "#41dfff",
             "Quil" = "#46eefa")


# change facet labels 
native_label <- c("native english speakers", "non-native english speakers")
names(native_label) <- c("Yes", "No")

# text

t_text <- "AI-Text Dectectors are Biased Against Non-Native Speakers"
st_text <- "While most AI-text detectors boast about their near-perfect accuracy at distinguishing 
            text generated by humans or AI, they leave out an important part. The majority of these detectors 
            flag content as AI-generated when it comes from non-native English speakers. 
            When tested on the Test of English as a Foreign Language (TOEFL) essays from a Chinese forum,
            these **detectors showed only 24-52% accuracy** in denoting them as human-generated content."
c_text <- "Source: TidyTuesday (Liang et al, DOI:10.1016/j.patter.2023.100779) • Graphic: Sejal Davla, PhD"

# plot

gpt_detector_plot <- human_summary |>
  filter(pred_class == "Human") |>
  mutate(native = factor(native, levels = c("Yes", "No"))) |>
  ggplot(aes(x = fct_reorder(detector, percent), y = percent, fill = detector)) +
  geom_col(color = "white", 
           width = 1, 
           position = "identity", 
           linewidth = 1.2) +
  geom_text(aes(y = percent + 7, label = paste0(percent, "%")),
            size = 8,
            family = "brassmono") +
  coord_polar(clip = "off") +
  facet_wrap(~ native,
             labeller = labeller(native = native_label)) +
  scale_y_continuous(limits = c(0, 110),
                     breaks = seq(0, 110, 50)) +
  scale_fill_manual(values = col_pal,
                    labels = c("<span style = 'color:#d16ba5'>**ZeroGPT**</span> is a  ChatGPT, GPT4 & AI content detector",
                                "<span style = 'color:#ba83ca'>**GPTZero**</span> is trained to detect ChatGPT, GPT4, Bard, LLaMa, and other AI models",
                                "<span style = 'color:#aa8fd8'>**Crossplag**</span> is a **plagiarism and AI detection tool in academic publishing**",
                                "<span style = 'color:#8aa7ec'>**HFOpenAI**</span> is an AI text generator",
                                "<span style = 'color:#69bff8'>**Sapling**</span> is a spelling and grammar checker",
                                "<span style = 'color:#46eefa'>**Quill**</span> is an AI text generator",
                                "<span style = 'color:#41dfff'>**OriginalityAI**</span> is an **AI content detection tool for web publishers**")) +
  labs(title = t_text,
       subtitle = st_text,
       caption = c_text,
       fill = NULL) +
  theme_minimal() +
  theme(plot.background = element_rect(fill = "white",
                                       color = "white"),
        plot.title = element_markdown(family = "datacontrol",
                                      size = 45,
                                      color = "#74AA9C",
                                      margin = margin(0,0,0.7,0, unit = "cm")),
        plot.subtitle = element_textbox_simple(family = "Ubuntu Mono",
                                               size = 25,
                                               lineheight = 0.5,
                                               margin = margin(0,0,1,0, unit = "cm")),
        plot.caption = element_text(family = "brassmono",
                                    size = 20,
                                    color = "#74AA9c",
                                    hjust = 0.5),
        plot.title.position = "plot",
        panel.background = element_rect(fill = "white",
                                        color = "white"),
        panel.border = element_blank(),
        panel.grid = element_blank(),
        panel.spacing = unit(0.5, "lines"),
        axis.line = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        legend.position = "bottom",
        legend.text = element_blank(),
        strip.text = element_markdown(size = 23,
                                      family = "datacontrol",
                                      color = "#74AA9C"),
        strip.background = element_roundrect(color = "grey80",
                                        r = 0.20)) +
  guides(fill = guide_legend(nrow = 7,
                             keywidth = 0.7,
                             keyheight = 0.7,
                             label.theme = element_markdown(family = "Ubuntu Mono",
                                                        size = 25)))

# save plot

ggsave("gpt_detector_plot.png", width = 6, height = 6, units = "in", dpi = 300)






